# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GSM.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'GSM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tGSM.proto\"<\n\x06MyCell\x12\x0b\n\x03MCC\x18\x01 \x01(\x03\x12\x0b\n\x03MNC\x18\x02 \x01(\x03\x12\x0b\n\x03\x43ID\x18\x03 \x01(\x03\x12\x0b\n\x03LAC\x18\x04 \x01(\x03\"T\n\x0f\x43\x65llReqToApple1\x12\x15\n\x04\x63\x65ll\x18\x01 \x03(\x0b\x32\x07.MyCell\x12\x0e\n\x06param3\x18\x03 \x01(\x03\x12\x0e\n\x06param4\x18\x04 \x01(\x03\x12\n\n\x02ua\x18\x05 \x01(\t\"M\n\x10\x43\x65llReqToApple25\x12\x15\n\x04\x63\x65ll\x18\x19 \x02(\x0b\x32\x07.MyCell\x12\x10\n\x08unknown3\x18\x03 \x01(\x03\x12\x10\n\x08unknown4\x18\x04 \x01(\x03\"\xee\x01\n\rCellResponse1\x12\x0b\n\x03MCC\x18\x01 \x01(\x03\x12\x0b\n\x03MNC\x18\x02 \x01(\x03\x12\x0b\n\x03\x43ID\x18\x03 \x01(\x03\x12\x0b\n\x03LAC\x18\x04 \x01(\x03\x12)\n\x08location\x18\x05 \x01(\x0b\x32\x17.CellResponse1.Location\x12\x0f\n\x07\x63hannel\x18\x0b \x01(\x03\x12\x0e\n\x06\x64\x61ta12\x18\x0c \x01(\x03\x1a]\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x02(\x03\x12\x11\n\tlongitude\x18\x02 \x02(\x03\x12\r\n\x05\x64\x61ta3\x18\x03 \x01(\x03\x12\r\n\x05\x64\x61ta4\x18\x04 \x01(\x03\x12\x0e\n\x06\x64\x61ta12\x18\x0c \x01(\x03\"\xe5\x01\n\x0e\x43\x65llResponse22\x12\x0b\n\x03MCC\x18\x01 \x01(\x03\x12\x0b\n\x03MNC\x18\x02 \x01(\x03\x12\x0b\n\x03\x43ID\x18\x03 \x01(\x03\x12\x0b\n\x03LAC\x18\x04 \x01(\x03\x12*\n\x08location\x18\x05 \x01(\x0b\x32\x18.CellResponse22.Location\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\x03\x1a\x62\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x02(\x03\x12\x11\n\tlongitude\x18\x02 \x02(\x03\x12\x12\n\nconfidence\x18\x03 \x01(\x03\x12\r\n\x05\x64\x61ta4\x18\x04 \x01(\x03\x12\x0e\n\x06\x64\x61ta12\x18\x0c \x01(\x03\"4\n\x13\x43\x65llInfoFromApple22\x12\x1d\n\x04\x63\x65ll\x18\x16 \x03(\x0b\x32\x0f.CellResponse22\"2\n\x12\x43\x65llInfoFromApple1\x12\x1c\n\x04\x63\x65ll\x18\x01 \x03(\x0b\x32\x0e.CellResponse1')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GSM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYCELL']._serialized_start=13
  _globals['_MYCELL']._serialized_end=73
  _globals['_CELLREQTOAPPLE1']._serialized_start=75
  _globals['_CELLREQTOAPPLE1']._serialized_end=159
  _globals['_CELLREQTOAPPLE25']._serialized_start=161
  _globals['_CELLREQTOAPPLE25']._serialized_end=238
  _globals['_CELLRESPONSE1']._serialized_start=241
  _globals['_CELLRESPONSE1']._serialized_end=479
  _globals['_CELLRESPONSE1_LOCATION']._serialized_start=386
  _globals['_CELLRESPONSE1_LOCATION']._serialized_end=479
  _globals['_CELLRESPONSE22']._serialized_start=482
  _globals['_CELLRESPONSE22']._serialized_end=711
  _globals['_CELLRESPONSE22_LOCATION']._serialized_start=613
  _globals['_CELLRESPONSE22_LOCATION']._serialized_end=711
  _globals['_CELLINFOFROMAPPLE22']._serialized_start=713
  _globals['_CELLINFOFROMAPPLE22']._serialized_end=765
  _globals['_CELLINFOFROMAPPLE1']._serialized_start=767
  _globals['_CELLINFOFROMAPPLE1']._serialized_end=817
# @@protoc_insertion_point(module_scope)
